version: 2

defaults: &defaults
  docker:
    - image: circleci/android:api-27-alpha
  working_directory: ~/code
  environment:
    JAVA_TOOL_OPTIONS: "-Xmx3200m"
    GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2 -Dkotlin.incremental=false"
    TERM: dumb

jobs:
  build:
    steps:
      - checkout
      - run:
          name: Give gradlew write
          command: chmod +x gradlew
      - run:
          name: Generate cache key
          command: ./ciUtil/checksum.sh /tmp/checksum.txt
      - restore_cache:
          key: gradle-{{ checksum "/tmp/checksum.txt" }}
      - run:
          name: Give gradlew write
          command: chmod +x gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-{{ checksum "/tmp/checksum.txt" }}
      - run:
          name: Assemble apk
          command: ./gradlew :app:assembleApp --profile
      - store_artifacts:
          path: app/build/outputs/mapping/app/release/mapping.txt
          destination: mapping
      - store_artifacts:
          path: app/build/outputs/apk/app/release
          destination: apk
      - store_artifacts:
          path: app/build/outputs/apk/app/debug
          destination: apk
      - store_artifacts:
          path: build/reports/profile
          destination: gradleProfile
      - store_artifacts:
          path: build/reports/profile/css
          destination: gradleProfile/css
      - store_artifacts:
          path: build/reports/profile/js
          destination: gradleProfile/js
      - run:
          name: Run Tests
          command: ./gradlew lint test
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results
