version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-28-alpha
    environment:
      JVM_OPTS: -Xmx3200m
      GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2 -Dkotlin.incremental=false"
    steps:
      - checkout
      - run:
          name: Give script write
          command: chmod +x ./ciUtil/checksum.sh
      - run:
          name: Generate cache key
          command: ./ciUtil/checksum.sh /tmp/checksum.txt
      - restore_cache:
          key: gradle-{{ checksum "/tmp/checksum.txt" }}
      - run:
          name: Give gradlew write
          command: chmod +x gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-{{ checksum "/tmp/checksum.txt" }}
      - run:
          name: Assemble apk
          command: ./gradlew :app:assembleApp
      - store_artifacts:
          path: app/build/outputs/apk/app/release
          destination: apk
      - store_artifacts:
          path: app/build/outputs/apk/app/debug
          destination: apk
      - run:
          name: Run Tests
          command: ./gradlew lint test
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results
